CREATE TABLE ESTADO (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
SIGLA TEXT(2) NOT NULL UNIQUE,
NOME TEXT(64) NOT NULL
);

CREATE TABLE CIDADE (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
NOME TEXT(128) NOT NULL,
ESTADO_ID INTEGER NOT NULL,
CONSTRAINT ESTADO_fk FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO(ID)
);

CREATE TABLE CLIENTE (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
NOME TEXT(128) NOT NULL,
NASCIMENTO TEXT(10) NOT NULL,
CIDADE_ID INTEGER NOT NULL,
CONSTRAINT CIDADE_fk FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE(ID)
);