CREATE DATABASE DB_Autores

CREATE TABLE USUARIO (
COD_USUARIO INT PRIMARY KEY,
NOME_USUARIO VARCHAR(30),
TELEFONE_USUARIO CHAR(13),
ENDERECO_USUARIO VARCHAR(100)
);

CREATE TABLE AUTOR (
COD_AUTOR INT PRIMARY KEY,
NOME_AUTOR VARCHAR(30),
TELEFONE_AUTOR CHAR(13),
ENDERECO_AUTOR VARCHAR(100)
);

CREATE TABLE EDITORAS (
COD_EDITORA INT PRIMARY KEY,
NOME_EDITORA VARCHAR(30),
TELEFONE_EDITORA CHAR(13),
ENDERECO_EDITORA VARCHAR(100)
);

CREATE TABLE EDITOR (
COD_EDITOR INT PRIMARY KEY,
NOME_EDITOR VARCHAR(30),
TELEFONE_EDITOR CHAR(13),
ENDERECO_EDITOR VARCHAR(100)
);

CREATE TABLE AREA_CONHECIMENTO (
COD_AREA_CONHECIMENTO INT PRIMARY KEY,
NOME_AREA_CONHECIMENTO VARCHAR(20)
);

CREATE TABLE TITULOS (
COD_TITULO INT PRIMARY KEY,
NOME_TITULO VARCHAR(50),
TIPO_TITULO VARCHAR(20),
COD_AREA_CONHECIMENTO INT REFERENCES AREA_CONHECIMENTO(COD_AREA_CONHECIMENTO) NOT NULL
);

CREATE TABLE EXEMPLAR (
COD_EXEMPLAR INT PRIMARY KEY,
COD_TITULO INT REFERENCES TITULOS(COD_TITULO) NOT NULL
);

CREATE TABLE PALAVRA_CHAVE (
COD_PALAVRA_CHAVE INT PRIMARY KEY,
DESCRICAO_PALAVRA_CHAVE VARCHAR(20)
);

CREATE TABLE REVISTA (
COD_REVISTA INT PRIMARY KEY,
TIPO_REVISTA CHAR(4),
COD_TITULO INT REFERENCES TITULOS(COD_TITULO) NOT NULL
);

CREATE TABLE MIDIA (
COD_MIDIA INT PRIMARY KEY,
TIPO_MIDIA CHAR(4),
COD_TITULO INT REFERENCES TITULOS(COD_TITULO) NOT NULL
);

CREATE TABLE LIVRO (
COD_LIVRO INT PRIMARY KEY,
TIPO_LIVRO CHAR(4),
COD_TITULO INT REFERENCES TITULOS(COD_TITULO) NOT NULL
);

CREATE TABLE USUARIO_EXEMPLAR (
COD_EMPRESTIMO INT PRIMARY KEY,
DATA_EMPRESTIMO DATETIME,
DATA_DEVOLUCAO DATETIME,
COD_USUARIO INT REFERENCES USUARIO(COD_USUARIO) NOT NULL,
COD_EXEMPLAR INT REFERENCES EXEMPLAR(COD_EXEMPLAR) NOT NULL,
COD_TITULO INT REFERENCES TITULOS(COD_TITULO) NOT NULL,
UNIQUE(COD_EXEMPLAR, COD_TITULO)
);

CREATE TABLE AUTOR_LIVRO (
COD_AUTOR INT REFERENCES AUTOR(COD_AUTOR) NOT NULL,
COD_TITULO INT REFERENCES TITULOS(COD_TITULO) NOT NULL,
UNIQUE(COD_AUTOR, COD_TITULO)
);

CREATE TABLE EDITORAS_LIVRO (
COD_EDITORA INT REFERENCES EDITORAS(COD_EDITORA) NOT NULL,
COD_TITULO INT REFERENCES TITULOS(COD_TITULO) NOT NULL,
UNIQUE(COD_EDITORA, COD_TITULO)
);

CREATE TABLE EDITOR_REVISTA (
COD_EDITOR INT REFERENCES EDITOR(COD_EDITOR) NOT NULL,
COD_REVISTA INT REFERENCES REVISTA(COD_REVISTA) NOT NULL,
UNIQUE(COD_EDITOR, COD_REVISTA)
);

CREATE TABLE EDITOR_MIDIA (
COD_EDITOR INT REFERENCES EDITOR(COD_EDITOR) NOT NULL,
COD_MIDIA INT REFERENCES MIDIA(COD_MIDIA) NOT NULL,
UNIQUE(COD_EDITOR, COD_MIDIA)
);

CREATE TABLE PALAVRA_CHAVE_TITULOS (
COD_PALAVRA_CHAVE INT REFERENCES PALAVRA_CHAVE(COD_PALAVRA_CHAVE) NOT NULL,
COD_TITULO INT REFERENCES TITULOS(COD_TITULO) NOT NULL,
UNIQUE(COD_PALAVRA_CHAVE, COD_TITULO)
);
