CREATE TABLE Bd_Museu

create table PAIS (
COD_PAIS INT PRIMARY KEY,
NOME_PAIS VARCHAR(30) NOT NULL)

CREATE TABLE MUSEU(
COD_MUSEU INT PRIMARY KEY,
NOME_MUSEU VARCHAR (30) NOT NULL,
COD_PAIS INT REFERENCES PAIS NOT NULL)

CREATE TABLE AUTOR(
COD_AUTOR INT PRIMARY KEY,
NOME_AUTOR VARCHAR (50),
COD_PAIS INT REFERENCES PAIS,
DATA_NASCIMENTO_AUTOR DATETIME)

CREATE TABLE ESCOLA (
COD_ESCOLA INT PRIMARY KEY,
NOME_ESCOLA VARCHAR (15)NOT NULL)

CREATE TABLE AUTORIA (
COD_AUTORIA INT PRIMARY KEY,
COD_AUTOr INT REFERENCES AUTOR NOT NULL,
COD_ESCOLA INT REFERENCES ESCOLA NOT NULL,
DATA_INICIO_ESCOLA DATETIME NOT NULL,
DATA_FIM_ESCOLA DATETIME,
UNIQUE (COD_ESCOLA, COD_AUTOR))

CREATE TABLE OBRA (
COD_OBRA INT PRIMARY KEY,
NOME_OBRA VARCHAR (200) NOT NULL,
COD_MUSEU INT REFERENCES MUSEU NOT NULL,
COD_ESCOLA INT NOT NULL,
COD_AUTORIA INT REFERENCES AUTORIA NOT NULL)

