CREATE DATABASE DbPASTELARIA
CREATE TABLE USUARIOS (
ID INTEGER PRIMARY KEY NOT NULL,
);

CREATE TABLE PRODUTOS (
ID INTEGER PRIMARY KEY NOT NULL,
);

CREATE TABLE MESAS (
ID INTEGER PRIMARY KEY NOT NULL,
);

CREATE TABLE COMANDAS (
ID INTEGER PRIMARY KEY NOT NULL,
MESA_ID INTEGER NOT NULL,
CONSTRAINT MESAS_fk FOREIGN KEY (MESA_id) REFERENCES MESAS(ID)
);

CREATE TABLE PEDIDOS (
ID INTEGER PRIMARY KEY NOT NULL,
COMANDA_ID INTEGER NOT NULL,
CONSTRAINT COMANDA_fk FOREIGN KEY (COMANDA_ID) REFERENCES COMANDAS(ID)
);

CREATE TABLE ITENS_PEDIDO (
ID INTEGER PRIMARY KEY NOT NULL,
PEDIDO_ID INTEGER NOT NULL,
PRODUTO_ID INTEGER NOT NULL,
CONSTRAINT PEDIDO_fk FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOS(ID),
CONSTRAINT PRODUTOS_fk FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(ID)
);